trop_notes = {
    'munach-zarka': [-5, 0],
    'zarka': [5, 3, 2, 0],
    'munach-segol': [-5, 0],
    'segol': [0, -2, -5. -7, -5],
    'munach-munach-rvii': [-5, 2, 0],
    'munach-rvii': [-5, 2, 0],
    'rvii': [0, -2, -5. -2, -5],
    'mapakh': [0, -5],
    'pashta': [-5, 2, 0],
    'munach-katon': [0, -5, 3, 2],
    'zakef-katon': [0, 2, -2],
    'zakef-gadol': [5, -5, 0],
    'mercha': [-5, -2],
    'tipcha': [0, 2, -2, -5],
    'munach-etnachta': [-5, -2],
    'etnachta': [-5, -2, 2, 0,],
    'pazar': [-5, 0, 2, 3, 2, 5, 3, 2, 0, 2, 0],
    'tlisha-ktana': [-5, -3, -2, -3, -2, -5],
    'tlisha-gdola': [-5, -3, -2, -3, -2, -5],
    'kadma': [-5, 0],
    'vazla': [0, 2, 3, 0, 5, 0],
    'azla-geresh': [0, 2, 5, 0],
    'gershaim': [0, 2, 3, 2, 0, 2, 0],
    'darga': [0, 5, 3, 2, 0],
    'tvir': [0, -5, -7, -2],
    'yetiv': [5, 0],
    'munach': [-5, 2, 0],
    'shalshelet': [],
    'sof-pasuk': [-2, 0, -2, -5]
}

trop_name = {
    'munach-zarka': ['Mu', 'nach'],
    'zarka': ['Zar', 'ka', 'a', 'a', 'a', 'a'],
    'munach-segol': ['Mu', 'nach'],
    'segol': ['Se', 'go', 'o', 'o', 'o', 'ol'],
    'munach-munach-rvii': ['Mu', 'na', 'ach'],
    'munach-rvii': ['Mu', 'na', 'ach'],
    'rvii': ['R\'vi','i','i','i','i'],
    'mapakh': ['Mapa', 'akh'],
    'pashta': ['Pash', 'ta', 'a'],
    'munach-katon': ['Muna','a','a','ach'],
    'zakef-katon': ['Ka','to','on'],
    'zakef-gadol': ['Zakef Ga', 'do', 'o', 'ol'],
    'mercha': ['Mer', 'cha'],
    'tipcha': ['Tip', 'cha', 'a', 'a'],
    'munach-etnachta': ['Mu', 'nach'],
    'etnachta': ['Et', 'nach', 'ta', 'a'],
    'pazer': ['Pa', 'ze', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'er'],
    'tlisha-ktana': ['Tlisha Ktana', 'a', 'a', 'a', 'a', 'a'],
    'tlisha-gdola': ['Tlisha Gedola', 'a', 'a', 'a', 'a', 'a'],
    'kedma': ['Kad', 'ma'],
    'vazla': ['V\'', 'az', 'la', 'a', 'a', 'a'],
    'azla-geresh': ['Az', 'la', 'ge', 'resh'],
    'gershaim': ['Gershai', 'i', 'i', 'i', 'i', 'im'],
    'darga': ['Darga', 'a', 'a', 'a'],
    'tvir': ['T\'', 'vi', 'i', 'i', 'ir'],
    'yetiv': ['Yeti', 'iv'],
    'munach': ['Mu', 'na', 'ach'],
    'sof-pasuk': ['Sof Pasu', 'u', 'uk']
}